# Generated by Django 4.2.4 on 2023-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('love', 'Love'), ('sci-fi', 'Science Fiction')], max_length=250, null=True),
        ),
    ]
